# Generated by Django 5.1.3 on 2024-11-30 10:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b747cc03-1b8e-423e-957d-a38a561e4d4f'), editable=False, primary_key=True, serialize=False),
        ),
    ]
