# Generated by Django 5.1.3 on 2024-12-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subject', '0002_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=45, unique=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
