# Generated by Django 5.1.3 on 2024-12-09 06:27

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_head_of_department'),
        ('subject', '0003_alter_subject_code_alter_subject_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=45),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('code'), name='unique_lower_code'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), name='unique_lower_name'),
        ),
    ]
