# Generated by Django 5.1.3 on 2024-12-05 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_rename_head_of_dep_department_head_of_department'),
        ('teacher', '0003_remove_teacher_first_name_remove_teacher_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='head_of_department',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='teacher.teacher'),
        ),
    ]
