# Generated by Django 5.1.3 on 2024-11-25 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='3LOabGDc4hTcTYPefX45knCSHbYaP3GE', max_length=32),
        ),
    ]
