# Generated by Django 5.1.3 on 2024-12-11 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ll68TTxLAvfPEPHYzm283yXmxxiMCoOJ', max_length=32),
        ),
    ]
