# Generated by Django 5.1.3 on 2024-12-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='JfPLzX1cCDcYvXtsDpb3eeeK3QLgDTmK', max_length=32),
        ),
    ]
