# Generated by Django 5.1.3 on 2024-11-27 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='zDShpHJwQ6nGc3UILDmAPjd7k9fnTkLt', max_length=32),
        ),
    ]
