# Generated by Django 5.1.3 on 2024-12-20 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='adsEIfKgps4NMZ2C5hEGfow5VUeQYy5D', max_length=32),
        ),
    ]
