# Generated by Django 5.1.3 on 2024-11-30 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0004_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='wKyW3uuFsj589CGr9bDDQ1VcaAmBpzUi', max_length=32),
        ),
    ]
