# Generated by Django 5.1.3 on 2024-12-01 04:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
        ('home_auth', '0005_create_default_groups'),
    ]

    operations = [
    ]
