# Generated by Django 5.1.3 on 2024-12-20 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0005_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='vXa4WgyVTzO8bkoFjn6qbsI7nbJ572ZD', max_length=32),
        ),
    ]
