# Generated by Django 5.1.3 on 2024-12-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0008_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='0groXJYxpRg72ru91InUGW8SUEpdvb4D', max_length=32),
        ),
    ]
