# Generated by Django 5.1.3 on 2024-12-01 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0009_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='xeKeuc25kMn2bdeqy5wYUR9D5OQTSTGZ', max_length=32),
        ),
    ]
