# Generated by Django 5.1.3 on 2024-12-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0013_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ml1P6hZSuQLT0CIL9oz7yQuVHThYbwDe', max_length=32),
        ),
    ]
