# Generated by Django 5.1.3 on 2024-12-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0014_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='gPhlbJalZicKXAqyxhx87udu5o4Ih5SF', max_length=32),
        ),
    ]
