# Generated by Django 5.1.3 on 2024-12-01 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0015_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='k5ZE7pyqs90e9tMQWB26AKMgtwl5pJ6D', max_length=32),
        ),
    ]
