# Generated by Django 5.1.3 on 2024-12-01 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0016_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='mtpgLj1mhi9KjzG6kjxN8OFwq2QkBRfL', max_length=32),
        ),
    ]
