# Generated by Django 5.1.3 on 2024-12-06 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0020_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='GZHuFSC4mia1dDmqFzo78OjCSyb1VsUc', max_length=32),
        ),
    ]
