# Generated by Django 5.1.3 on 2024-12-06 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0021_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='XStiBnDbJC1zblaC82LnnOKOeWtq9Qx8', max_length=32),
        ),
    ]
