# Generated by Django 5.1.3 on 2024-12-08 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0022_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='M48h68qmfoZdrhbCBI4JBQRyaTowxqkT', max_length=32),
        ),
    ]
