# Generated by Django 5.1.3 on 2024-12-08 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0023_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='wJF1Zg31YE7fFcFXW2WjQv7OlkfJx1gp', max_length=32),
        ),
    ]
