# Generated by Django 5.1.3 on 2024-12-09 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0025_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='ltrytYLnWXtyBIVzrrVqD45rVuct2jkL', max_length=32),
        ),
    ]
