# Generated by Django 5.1.3 on 2024-12-09 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0026_alter_passwordresetrequest_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='xSqTqTyj43hdufZO5UhIBKvISpfBiXNf', max_length=32),
        ),
    ]
